<?php

namespace AppBundle\Entity;

/**
 * AlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlarmRepository extends \Doctrine\ORM\EntityRepository {

    public function findalarm($name, $fromDate) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.user = :user')
                ->andWhere('c.alarmAt < :fromDate')
                ->addOrderBy('c.id')
                ->setParameters(array('user' => $name, 'fromDate' => $fromDate,))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getOneOrNullResult();
    }

}
