<?php

namespace AppBundle\Entity;

/**
 * EtemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ElistTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}