<?php

namespace AppBundle\Entity;

/**
 * EmailTaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailTaskRepository extends \Doctrine\ORM\EntityRepository
{
    public function findallbycampid($campid) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.campId = :campid')
                ->addOrderBy('c.id')
                ->setParameters(array('campid' => $campid));

        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function findByDone($done) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.done = :done')
                ->setParameters(array('done' => $done));

        try {
            return $qb->getQuery()->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
}
