<?php

namespace AppBundle\Entity;

/**
 * InboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboxRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findolderOneMonth($startdate) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.createdAt < :startdate')
                ->setParameters(array('startdate' => $startdate));

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function countAll() {

        $qb = $this->createQueryBuilder('c')
                ->select('count(c)');
               
        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
    
    

}
