<?php

namespace AppBundle\Entity;

/**
 * LoghistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LoghistoryRepository extends \Doctrine\ORM\EntityRepository
{   
    public function findmyloghistorybyid($id) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.logid = :id')
                ->addOrderBy('c.id')
                ->setParameters(array('id' => $id));

        return $qb->getQuery()
                        ->getResult();
    }
}
