<?php

namespace AppBundle\Entity;

/**
 * MainfolderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainfolderRepository extends \Doctrine\ORM\EntityRepository
{
    public function findallfolder($id) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.settid = :id')
                ->setParameters(array('id' => $id));

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function findallfolderName($id) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.settid = :id')
                ->setParameters(array('id' => $id));

        return $qb->getQuery()
                        ->getResult();
    }
}
