<?php

namespace AppBundle\Entity;

/**
 * MainattachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainattachmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function findmyattachments($id) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.maininbox = :id')
                ->setParameters(array('id' => $id));

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function countattachmentsbyemailid($id) {

        $qb = $this->createQueryBuilder('c')
                ->select('count(c)')
                ->where('c.maininbox = :id')
                //->addOrderBy('c.id')
                ->setParameters(array('id' => $id));

        return $qb->getQuery()
                        ->getSingleScalarResult();
    }
}
