<?php

namespace AppBundle\Entity;

/**
 * MainfilterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainfilterRepository extends \Doctrine\ORM\EntityRepository
{
    public function findallspam() {

        $qb = $this->createQueryBuilder('c')
                ->select('c.filtertext')
                ->addOrderBy('c.id', 'DESC')
                ->where('c.type = :type')
                ->setParameters(array('type' => 1));

        return $qb->getQuery()
                        ->getResult();
    }
    
}
