<?php

namespace AppBundle\Entity;

/**
 * MainstarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainstarRepository extends \Doctrine\ORM\EntityRepository {

    public function findmystar($id, $name) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.inboxid = :id', 'c.username = :username')
                ->setParameters(array('id' => $id, 'username' => $name))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getResult();
        
    }
    
    public function findmyAllstar($id, $name) {
        $qb = $this->createQueryBuilder('c')
                ->select('c.inboxid')
                ->where('c.settid = :id', 'c.username = :username')
                ->setParameters(array('id' => $id, 'username' => $name));

        return $qb->getQuery()
                        ->getResult();
        
    }
    
    public function findmystarByNameRange($id, $name, $startid, $finishid) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.settid = :id', 'c.username = :username')
                ->andWhere('c.inboxid <= :startid', 'c.inboxid >= :finishid')
                ->setParameters(array('id' => $id, 'username' => $name, 'startid' => $startid, 'finishid' => $finishid));
                //->setMaxResults(1);

        return $qb->getQuery()
                        ->getResult();
        
    }
    

}
