<?php

namespace AppBundle\Entity;

/**
 * MaincontactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaincontactRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneEmail($fromEmail) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.email = :fromEmail')
                ->setParameters(array('fromEmail' => $fromEmail))
                ->setMaxResults(1);

        return $qb->getQuery()
                        ->getResult();
    }
    
    public function autocomplete() {

        $qb = $this->createQueryBuilder('c')
                ->select('c.name', 'c.id', 'c.email')
                ->addOrderBy('c.id');
        return $qb->getQuery()
                        ->getResult();
    }
}
