<?php

namespace AppBundle\Entity;

/**
 * PricelistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricelistRepository extends \Doctrine\ORM\EntityRepository

{
    
}
