<?php

namespace AppBundle\Entity;

/**
 * ReviewsentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewsentRepository extends \Doctrine\ORM\EntityRepository
{
    public function countall() {
        $qb = $this->createQueryBuilder('c')
                ->select('count(c)')
                ;

        try {
            return $qb->getQuery()->getSingleScalarResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
     public function findConfSentbylimit($limit, $offset) {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id', 'ASC')
                ->setMaxResults($limit)
                ->setFirstResult($offset);

        try {
            return $qb->getQuery()->getResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
    
    public function searchLeadsByName($name) {

        $qb = $this->createQueryBuilder('n');
        $result = $qb->select('n')
                ->where($qb->expr()->like('n.customerName', $qb->expr()->literal('%' . $name . '%')))
                ->getQuery()
                ->getResult();
        return $result;
    }
    
    public function searchLeadsByEmail($email) {

        $qb = $this->createQueryBuilder('n');
        $result = $qb->select('n')
                ->where($qb->expr()->like('n.customerEmail', $qb->expr()->literal('%' . $email . '%')))
                ->getQuery()
                ->getResult();
        return $result;
    }
}
