<?php

namespace AppBundle\Entity;

/**
 * SettingsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findallsettings($username) {
        
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.username = :username')
                ->addOrderBy('c.id')
                ->setParameters(array('username' => $username));

        return $qb->getQuery()
                        ->getResult();
        
    }
    
    public function findallactive($active) {
        
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.active = :active')
                ->addOrderBy('c.id')
                ->setParameters(array('active' => $active));

        return $qb->getQuery()
                        ->getResult();
        
    }
    
    public function findallactiveIncoming($active) {
        
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->where('c.incoming = :active')
                ->addOrderBy('c.id')
                ->setParameters(array('active' => $active));

        return $qb->getQuery()
                        ->getResult();
        
    }
    
}
