<?php

namespace AppBundle\Entity;

/**
 * TexttemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TexttemplateRepository extends \Doctrine\ORM\EntityRepository
{
    public function findTemplates() {
        $qb = $this->createQueryBuilder('c')
                ->select('c');

        return $qb->getQuery()->getResult();
    }
}
