<?php

namespace AppBundle\Entity;

/**
 * TreatmentplanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TreatmentplanRepository extends \Doctrine\ORM\EntityRepository
{
}
