<?php

namespace AppBundle\Entity;

/**
 * UserlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findactivity($startdate, $finishdate, $username) {
        if($username === 'all') {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.createdAt > :startdate', 'c.createdAt < :finishdate')
                ->setParameters(array('startdate' => $startdate, 'finishdate' => $finishdate ));

        return $qb->getQuery()
                        ->getResult();
        } else {
            $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.createdAt > :startdate', 'c.createdAt < :finishdate', 'c.username = :username')
                ->setParameters(array('startdate' => $startdate, 'finishdate' => $finishdate, 'username' =>  $username,));

        return $qb->getQuery()
                        ->getResult();
        }
    }
}
