<?php

namespace AppBundle\Entity;

/**
 * UsermonitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsermonitorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findactivity($startdate, $finishdate) {

        $qb = $this->createQueryBuilder('c')
                ->select('c')
                ->addOrderBy('c.id')
                ->where('c.createdAt > :startdate', 'c.createdAt < :finishdate')
                ->setParameters(array('startdate' => $startdate, 'finishdate' => $finishdate ));

        return $qb->getQuery()
                        ->getResult();
    }
    
}
